### ISSUE TITLE
Animated theme doesn't support scrolling down

### ISSUE THREAD

**Issue by RTK23-dev** [finnie2006/PteroFreeStuffinstaller#1]
Hello.
The animated theme doesn't support scrolling down.
People are unable to scroll down in animated theme and if it possible to make mc theme more transparent that would be great!

**Comment by RTK23-dev** [comment]
Any eta when this will be fixed?

**Comment by finnie2006** [comment]
Nope sadly enough

**Comment by RTK23-dev** [comment]
> Nope sadly enough

Rip okay will wait i will try to fix myself whenever i get time
