### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by TekExplorer** [finnie2006/PteroFreeStuffinstaller#12]
Please put more info into the README.md. i have no idea what is in this repo or what it does, what addons, what themes, etc

**Comment by RTK23-dev** [comment]
You can make a pull request then or contact on discord no need to open that many issues :)

**Comment by TekExplorer** [comment]
this... is what issues are for...
im not making a PR cause i *dont know what most of these are or what they look like*
i've made ONE issue for it to bring the 'problem' (aka issue) to your attention.

please take that into consideration - im asking cause i dont know, and because i feel that adding info to the readme or another .md would be ideal :)

**Comment by RTK23-dev** [comment]
Okay we will do soon.

**Comment by finnie2006** [comment]
Will be added

**Comment by JohnB17** [comment]
I believe I have satisfied this request. If not, please reopen this issue or open another one (if needed) and respond with what is wrong and we will fix it.
