### ISSUE TITLE
McPaste button is not themed

### ISSUE THREAD

**Issue by ririko5834** [finnie2006/PteroFreeStuffinstaller#15]
Hi, how I need to modify the theme css files to theme also the mc paste button?
![image](https://user-images.githubusercontent.com/64729293/123432326-8e279180-d5ca-11eb-9099-7404abe34b4d.png)

**Comment by RTK23-dev** [comment]
Yeah it isn't

**Comment by RTK23-dev** [comment]
You can't change its colour if you do panel dosent loads and I have already talked about this to developers and they are working on it you may close this issue or wait.

**Comment by RTK23-dev** [comment]
Bruh thats the difference in theme and addons they can't add mc paste to any single theme so they made it look like normal pterodactyl bg colour if you like it then use, if you don't no one is forcing you.

**Comment by RTK23-dev** [comment]
You can't change colour of it till now

**Comment by ririko5834** [comment]
Ok, hope that your themes will include theming also of that button in the future

**Comment by finnie2006** [comment]
I will close this Because the Mcpaste button is not a default button from the panel so Not be added
