### ISSUE TITLE
Template no longer workign

### ISSUE THREAD

**Issue by Waffleuncle** [finnie2006/PteroFreeStuffinstaller#20]
Hi , 
Template installer is no longer working it causing blank page

**Comment by finnie2006** [comment]
Dark N Red works for me

**Comment by Waffleuncle** [comment]
What is you OS version on panel and your panel version ?

**Comment by Waffleuncle** [comment]
https://i.imgur.com/jM9Ic1o.png

**Comment by finnie2006** [comment]
Does it work after tgat error?

**Comment by JohnB17** [comment]
This error can safely be ignored. As for it being blank, more logs are needed.

**Comment by finnie2006** [comment]
I think this issue can be closed now
