### ISSUE TITLE
Stuck on installing

### ISSUE THREAD

**Issue by LonelyOfficial** [finnie2006/PteroFreeStuffinstaller#29]
``Done in 68.77s.
yarn run v1.22.17
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
``
I HAVE BEEN STUCK HERE

**Comment by finnie2006** [comment]
How long, this command can take up to 10 minutes

**Comment by LonelyOfficial** [comment]
its an hour & still its same

**Comment by finnie2006** [comment]
Stop it with Ctrl + C

Check the panel logs after: https://pterodactyl.io/panel/1.0/troubleshooting.html#reading-error-logs
