### ISSUE TITLE
Your discord in your readme.md is invalid

### ISSUE THREAD

**Issue by FreebieII** [finnie2006/PteroFreeStuffinstaller#30]
# When I try adding finniedj.exe#9075 it says its invalid.

Edit: Its a capital F

**Comment by finnie2006** [comment]
yeah sorry forgot to change it
did it now so closing the issue

**Comment by finnie2006** [comment]
Hmm opening it again, i am not sure what you mean but as i can see in every readme it already is F instead  of f
