### ISSUE TITLE
remove command

### ISSUE THREAD

**Issue by Kiku80** [finnie2006/PteroFreeStuffinstaller#37]
hey dude i want to remove the themes how can i ?

**Comment by finnie2006** [comment]
https://pterodactyl.io/panel/1.0/updating.html

**Comment by Kiku80** [comment]
why?

**Comment by finnie2006** [comment]
If you run the update command it will remove the theme

**Comment by Kiku80** [comment]
can u tell me the update command

**Comment by finnie2006** [comment]
> https://pterodactyl.io/panel/1.0/updating.html

..
