### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by saiswar5516T** [finnie2006/PteroFreeStuffinstaller#43]
i get issue when i use this setup my machine starts to lagg

**Comment by finnie2006** [comment]
Can you be more clear
- What did you install
- Is there a error or something

**Comment by saiswar5516T** [comment]
The mctheme

**Comment by finnie2006** [comment]
Did it install?
The theme should not make your server slower it just changes the colours

**Comment by JohnB17** [comment]
Do you mean that it lags during the install? That is fine, it can take a bit for the panel to build.

**Comment by sp-sketch** [comment]
yea, it made my vps pretty much slow asf

**Comment by finnie2006** [comment]
After build it should be fine, a theme can`t make your vps slower

**Comment by sp-sketch** [comment]
how to remove theme

**Comment by finnie2006** [comment]
Restore the backup
