### ISSUE TITLE
[Feature Request] Upload progress tracker

### ISSUE THREAD

**Issue by beastksoepic** [finnie2006/PteroFreeStuffinstaller#44]
I forked the repo and I added an upload progress tracker addon, it looks like this:
![image](https://user-images.githubusercontent.com/32767771/151356409-c75f6583-6129-4132-a495-b32ee2581aec.png)

I did not make this, it was originally created here:
https://github.com/pterodactyl/panel/pull/3687

Can I create a pr for this if I can?

**Comment by finnie2006** [comment]
I will not add something where i dont have the permissions for

**Comment by beastksoepic** [comment]
fair enough
