### ISSUE TITLE
Remove or Update MCPaste

### ISSUE THREAD

**Issue by Hitman4123** [finnie2006/PteroFreeStuffinstaller#46]
Either update the current version of MCPaste addon or remove it out right.

**Comment by JohnB17** [comment]
Right now, it just pulls the original author's install script.

**Comment by finnie2006** [comment]
Open

**Comment by Hitman4123** [comment]
Remove the old MCPaste files.

**Comment by Hitman4123** [comment]
_**Just remove the old mcpaste addon files (McPaste.tsx / ServerConsole.tsx).**_

**Comment by JohnB17** [comment]
The other changed how it is installed again, and we need to do the old way again.

**Comment by Hitman4123** [comment]
> 

What?

**Comment by JohnB17** [comment]
Sorry, the author changed how it is installed.

**Comment by finnie2006** [comment]
> Sorry, the author changed how it is installed.

You are literally talking to the author 😂

**Comment by Hitman4123** [comment]
### **Just Remove The Old Code....**
