### ISSUE TITLE
[BUG / Error]

### ISSUE THREAD

**Issue by aktoriblis** [finnie2006/PteroFreeStuffinstaller#59]
[https://buyer.qyuunee.my.id/]() **Did you run on a clean panel?**
(Pterodactyl did a major refactor a while back)
**Y/N**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Pterodactyl error log**
tail -n 1000 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | grep "\[$(date +%Y)"

**Comment by JohnB17** [comment]
Please provide the information requested.
